### PR TITLE
Implement simple dua group search. Some cleanup.

### PR DESCRIPTION
**Pull request by ahmedre**
i've implemented a really simple search based on the du3a group (we can easily change this to search the du3a table instead). i also did some minor cleanup while i was at it.
1. i removed the .idea files from git - these are per developer, so they shouldn't be in .git. note that this might cause your .idea files to be removed the first time you update, so you'd need to reimport the project into Android Studio (from then on, it will keep them and will not ask you to upload changes to those files to github).
2. renamed mySqliteDatabase - java classes should start with a capital letter. you also don't need to create an object if you are accessing static variables, so i fixed that too (and grouped the database constants in a way that better mimics what's there in your sqlite database).

there are several things that (in my opinion) still should be done - here are some:
1. the queries for both the du3a list and du3a details should be done on a worker thread instead of the ui thread.
2. i am not sure you really need AbsArrayAdapter
3. Settings crashes for me (due to getActionBar returning null).
4. you need a higher dpi search asset (it looks grainy on higher density screens).
5. some items don't have data (both in your current master version and with my patch).

happy to help with some of these if i can insha'Allah.

### CODE REVIEW

**Comment by khalid-hussain** [comment]
JazakAllahu khayran for your time and effort.
1. Thanks, I have no idea about this. Let me read into it..
2. I got this advice from [StackOverflow](http://stackoverflow.com/questions/27622039/listview-search-widget-filter?noredirect=1#comment43665961_27622039). I'm no expert but his blog has detailed why it's better.
3. It has yet to be implemented. I just added a skeleton to be filled in. I have yet to read into this too but I already have ideas for it.
4. I could not find the respective folders from this [repository](https://github.com/google/material-design-icons). I'm guessing the naming system has changed?
5. This is correct. I have halted filling the database to focus on 'search' and 'bookmark' functions.

Any help is appreciated even if it is just recommendations like number 1. I don't have experience in this field and any advice is most welcome.

**Comment by ahmedre** [comment]
1. he said, "extend `BaseAdapter`," which i agree with and that's what i am saying. that's different from extending `AbsArrayAdapter`.
2. i replaced the assets with https://github.com/google/material-design-icons/blob/master/action/drawable-xxxhdpi/ic_search_white_24dp.png

will send a pull request in a bit insha'Allah.

**Comment by khalid-hussain** [comment]
1. I'm sorry, I meant the [second reply](http://stackoverflow.com/questions/27622039/listview-search-widget-filter/27630681#27630681).

JazakAllahu khayran.

**Comment by ahmedre** [comment]
even for that reply, his suggestion is also using a `BaseAdapter` subclass (which we did). `BaseAdapter` is the standard way to do this, and even `ArrayAdapter` is a subclass of `BaseAdapter`.

**Pull request merged**
